### ISSUE TITLE
Guide 2 ikoner 

### ISSUE THREAD

**Issue by KikiAquaFox** [ChoopGod/MediaZone#47]
Lav 2 ikoner 

1 rød
1 blå

Plus text

**Comment by Nairtoch** [comment]
Hey @sondergaard2409 I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/mediazone-625eab4bc95a14001590c66c/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_
