### ISSUE TITLE
Underholdning overskift 

### ISSUE THREAD

**Issue by KikiAquaFox** [ChoopGod/MediaZone#52]
Overskrifterne skal laves - "Underholdning" - "Single Player" - "Multi Player" 
Husk streg under

**Comment by Nairtoch** [comment]
Hey @GyunaydanLyutvi I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/mediazone-625eab4bc95a14001590c66c/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_
